// Student Information


// Change these values to your own information.
const studentId = "YOUR STUDENT ID";
const studentName = "YOUR NAME";

// Find the paragraph on the HTML page.
const studentInfo = document.getElementById("studentInfo");

// Dynamically add the student ID and name to the page.
studentInfo.textContent = `Student ID: ${studentId} | Student Name: ${studentName}`;


// Pizza Class

/* The Pizza class represents a customer's pizza order. The constructor receives values captured from the form. */
class Pizza {
    constructor(
        customerName,
        email,
        size,
        crust,
        sauce,
        toppings,
        quantity,
        instructions
    ) {
        this.customerName = customerName;
        this.email = email;
        this.size = size;
        this.crust = crust;
        this.sauce = sauce;
        this.toppings = toppings;
        this.quantity = quantity;
        this.instructions = instructions;
    }

    /* This method creates and returns a complete description of the pizza order. The order displayed to the customer comes from this method. */
    getDescription() {
        // Display "No toppings" if the customer did not select any toppings.
        const toppingText = this.toppings.length > 0
            ? this.toppings.join(", ")
            : "No toppings";

        // Display "None" if no special instructions were entered.
        const instructionText = this.instructions.trim() !== ""
            ? this.instructions
            : "None";

        return `
            <h2>Order Confirmation</h2>
            <p><strong>Customer:</strong> ${this.customerName}</p>
            <p><strong>Email:</strong> ${this.email}</p>
            <p><strong>Pizza Size:</strong> ${this.size}</p>
            <p><strong>Crust:</strong> ${this.crust}</p>
            <p><strong>Sauce:</strong> ${this.sauce}</p>
            <p><strong>Toppings:</strong> ${toppingText}</p>
            <p><strong>Quantity:</strong> ${this.quantity}</p>
            <p><strong>Special Instructions:</strong> ${instructionText}</p>
            <p><strong>Thank you, ${this.customerName}! Your order has been received.</strong></p>
        `;
    }
}


// Form Submission

// Get references to the form and output section.
const pizzaForm = document.getElementById("pizzaForm");
const orderResult = document.getElementById("orderResult");

/* Listen for the form's submit event. */
pizzaForm.addEventListener("submit", function (event) {

    // Prevent the browser from refreshing the page.
    event.preventDefault();

    /* HTML validation happens automatically because required, type, minlength, min, and max are used in the HTML form.
       checkValidity() ensures that JavaScript continues only when all HTML validations pass. */
    if (!pizzaForm.checkValidity()) {
        pizzaForm.reportValidity();
        return;
    }

    
    // Capture Form Values

    // Capture customer information.
    const customerName =
        document.getElementById("customerName").value.trim();

    const email =
        document.getElementById("email").value.trim();

    // Capture pizza details.
    const size =
        document.getElementById("size").value;

    const crust =
        document.querySelector('input[name="crust"]:checked').value;

    const sauce =
        document.getElementById("sauce").value;

    // Capture all selected toppings.
    const toppingElements =
        document.querySelectorAll('input[name="toppings"]:checked');

    // Convert the selected checkboxes into an array.
    const toppings =
        Array.from(toppingElements).map(function (topping) {
            return topping.value;
        });

    // Capture quantity.
    const quantity =
        document.getElementById("quantity").value;

    // Capture special instructions.
    const instructions =
        document.getElementById("instructions").value.trim();


    // Create Pizza Object

    /* Create a new Pizza object using the values captured from the form. */
    const customerPizza = new Pizza(
        customerName,
        email,
        size,
        crust,
        sauce,
        toppings,
        quantity,
        instructions
    );


    // Display Order

    /* The order description is generated by invoking the getDescription() method on the Pizza object. */
    orderResult.innerHTML = customerPizza.getDescription();

    // Scroll to the order confirmation.
    orderResult.scrollIntoView({
        behavior: "smooth"
    });
});
